# Generated by Django 3.1.6 on 2021-02-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talepEdenKisi', models.CharField(max_length=100, verbose_name='Talep Eden')),
                ('talepEdildigiZaman', models.DateTimeField(verbose_name='Talep Edildiği Zaman')),
                ('talepUlasmasiGerektigiZaman', models.DateTimeField(verbose_name='Talep Bitiş Süresi')),
                ('Talep1', models.CharField(max_length=200, verbose_name='Talep-1')),
                ('talepKurumu1', models.CharField(max_length=120, verbose_name='Talebin Yapılacağı Kurum')),
                ('tutar1', models.FloatField(verbose_name='Talep Yaklasık Tutarı')),
                ('ihaletutar1', models.FloatField(blank=True, null=True, verbose_name='Firma Yaklasık Kalan Tutar')),
                ('Talep_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Talep-2')),
                ('talepKurumu_2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Talebin Yapılacağı Kurum2')),
                ('tutar_2', models.FloatField(blank=True, null=True, verbose_name='Talep Yaklasık Tutarı2')),
                ('ihaletutar_2', models.FloatField(blank=True, null=True, verbose_name='Firma Yaklasık Kalan Tutar2')),
                ('Talep_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Talep-3')),
                ('talepKurumu_3', models.CharField(blank=True, max_length=120, null=True, verbose_name='Talebin Yapılacağı Kurum3')),
                ('tutar_3', models.FloatField(blank=True, null=True, verbose_name='Talep Yaklasık Tutarı3')),
                ('ihaletutar_3', models.FloatField(blank=True, null=True, verbose_name='Firma Yaklasık Kalan Tutar3')),
                ('Talep_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Talep-4')),
                ('talepKurumu_4', models.CharField(blank=True, max_length=120, null=True, verbose_name='Talebin Yapılacağı Kurum4')),
                ('tutar_4', models.FloatField(blank=True, null=True, verbose_name='Talep Yaklasık Tutarı4')),
                ('ihaletutar_4', models.FloatField(blank=True, null=True, verbose_name='Firma Yaklasık Kalan Tutar4')),
                ('Talep_5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Talep-5')),
                ('talepKurumu_5', models.CharField(blank=True, max_length=120, null=True, verbose_name='Talebin Yapılacağı Kurum5')),
                ('tutar_5', models.FloatField(blank=True, null=True, verbose_name='Talep Yaklasık Tutarı5')),
                ('ihaletutar_5', models.FloatField(blank=True, null=True, verbose_name='Firma Yaklasık Kalan Tutar5')),
            ],
        ),
    ]
