# Generated by Django 3.1.6 on 2021-02-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talep',
            name='talepEdenKisi',
            field=models.CharField(default='BOŞ', max_length=100, verbose_name='Talep Eden'),
        ),
    ]
