# Generated by Django 3.1.6 on 2021-03-11 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talep', '0005_auto_20210221_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talep',
            name='talepEdenKisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden Kişi'),
        ),
    ]
