# Generated by Django 3.1.6 on 2021-03-11 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talep', '0006_auto_20210311_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='talep',
            name='Aciklama1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talep',
            name='Aciklama2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talep',
            name='Aciklama3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talep',
            name='onay1',
            field=models.BooleanField(default=False, verbose_name='Talep Onay'),
        ),
        migrations.AddField(
            model_name='talep',
            name='onay2',
            field=models.BooleanField(default=False, verbose_name='Talep Onay'),
        ),
        migrations.AddField(
            model_name='talep',
            name='onay3',
            field=models.BooleanField(default=False, verbose_name='Talep Onay'),
        ),
        migrations.AddField(
            model_name='talep',
            name='red1',
            field=models.BooleanField(default=False, verbose_name='Talep Red '),
        ),
        migrations.AddField(
            model_name='talep',
            name='red2',
            field=models.BooleanField(default=False, verbose_name='Talep Red '),
        ),
        migrations.AddField(
            model_name='talep',
            name='red3',
            field=models.BooleanField(default=False, verbose_name='Talep Red '),
        ),
        migrations.AddField(
            model_name='talep',
            name='tarih1',
            field=models.DateField(default=datetime.date.today, verbose_name='Talep Onay/Red Tarih'),
        ),
        migrations.AddField(
            model_name='talep',
            name='tarih2',
            field=models.DateField(default=datetime.date.today, verbose_name='Talep Onay/Red Tarih'),
        ),
        migrations.AddField(
            model_name='talep',
            name='tarih3',
            field=models.DateField(default=datetime.date.today, verbose_name='Talep Onay/Red Tarih'),
        ),
    ]
